// Code generated by xgen. DO NOT EDIT.

package xmltypes

// OtherAssociatedBodies ...
type OtherAssociatedBodies *OtherAssociatedBodiesType

// OtherAssociatedBodiesType ...
type OtherAssociatedBodiesType struct {
	TieAssociatedBody *AssociatedBodyType `xml:"AssociatedBody"`
}

// AssociatedBody ...
type AssociatedBody *AssociatedBodyType

// AssociatedBodyType ...
type AssociatedBodyType struct {
	AssociatedBodyName                  *InternationalNamesType       `xml:"AssociatedBodyName"`
	AssociatedBodyTradeName             *InternationalNamesType       `xml:"AssociatedBodyTradeName"`
	AssociatedBodyAddress               *AddressType                  `xml:"AssociatedBodyAddress"`
	AssociatedBodyInformationURI        *NonEmptyMultiLangURIListType `xml:"AssociatedBodyInformationURI"`
	AssociatedBodyInformationExtensions *ExtensionsListType           `xml:"AssociatedBodyInformationExtensions"`
}
