// Code generated by xgen. DO NOT EDIT.

package xmltypes

// InternationalNamesType ...
type InternationalNamesType struct {
	Name []*MultiLangNormStringType `xml:"Name"`
}

// MultiLangNormStringType ...
type MultiLangNormStringType struct {
	XmlLangAttr               *Lang `xml:"lang,attr"`
	*NonEmptyNormalizedString `xml:",chardata"`
}

// MultiLangStringType ...
type MultiLangStringType struct {
	XmlLangAttr     *Lang `xml:"lang,attr"`
	*NonEmptyString `xml:",chardata"`
}

// NonEmptyString ...
type NonEmptyString string

// NonEmptyNormalizedString ...
type NonEmptyNormalizedString string

// AddressType ...
type AddressType struct {
	LotePostalAddresses   *PostalAddressListType `xml:"PostalAddresses"`
	LoteElectronicAddress *ElectronicAddressType `xml:"ElectronicAddress"`
}

// PostalAddresses ...
type PostalAddresses *PostalAddressListType

// PostalAddressListType ...
type PostalAddressListType struct {
	LotePostalAddress []*PostalAddressType `xml:"PostalAddress"`
}

// PostalAddress ...
type PostalAddress *PostalAddressType

// PostalAddressType ...
type PostalAddressType struct {
	XmlLangAttr     *Lang   `xml:"lang,attr"`
	StreetAddress   string  `xml:"StreetAddress"`
	Locality        string  `xml:"Locality"`
	StateOrProvince *string `xml:"StateOrProvince"`
	PostalCode      *string `xml:"PostalCode"`
	CountryName     string  `xml:"CountryName"`
}

// ElectronicAddress ...
type ElectronicAddress *ElectronicAddressType

// ElectronicAddressType ...
type ElectronicAddressType struct {
	URI []*NonEmptyMultiLangURIType `xml:"URI"`
}

// AnyType ...
type AnyType struct {
	Content string `xml:",chardata"`
}

// Extension ...
type Extension *ExtensionType

// ExtensionType ...
type ExtensionType struct {
	CriticalAttr bool `xml:"Critical,attr"`
	*AnyType
}

// ExtensionsListType ...
type ExtensionsListType struct {
	LoteExtension []*ExtensionType `xml:"Extension"`
}

// NonEmptyURIType ...
type NonEmptyURIType string

// AttributedNonEmptyURIType ...
type AttributedNonEmptyURIType struct {
	TypeAttr *string `xml:"type,attr"`
	Value    string  `xml:",chardata"`
}

// NonEmptyMultiLangURIType ...
type NonEmptyMultiLangURIType struct {
	XmlLangAttr *Lang  `xml:"lang,attr"`
	Value       string `xml:",chardata"`
}

// NonEmptyMultiLangURIListType ...
type NonEmptyMultiLangURIListType struct {
	URI []*NonEmptyMultiLangURIType `xml:"URI"`
}

// NonEmptyURIListType ...
type NonEmptyURIListType struct {
	URI []string `xml:"URI"`
}

// ListOfTrustedEntities ...
type ListOfTrustedEntities *ListOfTrustedEntitiesType

// ListOfTrustedEntitiesType ...
type ListOfTrustedEntitiesType struct {
	LOTETagAttr                  string                            `xml:"LOTETag,attr"`
	IdAttr                       *string                           `xml:"Id,attr"`
	LoteListAndSchemeInformation *LoTEListAndSchemeInformationType `xml:"ListAndSchemeInformation"`
	LoteTrustedEntitiesList      *TrustedEntitiesListType          `xml:"TrustedEntitiesList"`
	DsSignature                  *Signature                        `xml:"ds:Signature"`
}

// TrustedEntitiesList ...
type TrustedEntitiesList *TrustedEntitiesListType

// TrustedEntitiesListType ...
type TrustedEntitiesListType struct {
	LoteTrustedEntity []*TEType `xml:"TrustedEntity"`
}

// ListAndSchemeInformation ...
type ListAndSchemeInformation *LoTEListAndSchemeInformationType

// LoTEListAndSchemeInformationType ...
type LoTEListAndSchemeInformationType struct {
	LoTEVersionIdentifier        int                           `xml:"LoTEVersionIdentifier"`
	LoTESequenceNumber           int                           `xml:"LoTESequenceNumber"`
	LoteLoTEType                 string                        `xml:"LoTEType"`
	LoteSchemeOperatorName       *InternationalNamesType       `xml:"SchemeOperatorName"`
	SchemeOperatorAddress        *AddressType                  `xml:"SchemeOperatorAddress"`
	LoteSchemeName               *InternationalNamesType       `xml:"SchemeName"`
	LoteSchemeInformationURI     *NonEmptyMultiLangURIListType `xml:"SchemeInformationURI"`
	StatusDeterminationApproach  string                        `xml:"StatusDeterminationApproach"`
	LoteSchemeTypeCommunityRules *NonEmptyMultiLangURIListType `xml:"SchemeTypeCommunityRules"`
	LoteSchemeTerritory          *string                       `xml:"SchemeTerritory"`
	LotePolicyOrLegalNotice      *PolicyOrLegalnoticeType      `xml:"PolicyOrLegalNotice"`
	HistoricalInformationPeriod  *int                          `xml:"HistoricalInformationPeriod"`
	LotePointersToOtherLoTE      *OtherLoTEPointersType        `xml:"PointersToOtherLoTE"`
	ListIssueDateTime            string                        `xml:"ListIssueDateTime"`
	LoteNextUpdate               *NextUpdateType               `xml:"NextUpdate"`
	LoteDistributionPoints       *NonEmptyURIListType          `xml:"DistributionPoints"`
	SchemeExtensions             *ExtensionsListType           `xml:"SchemeExtensions"`
}

// LoTEType ...
type LoTEType string

// SchemeOperatorName ...
type SchemeOperatorName *InternationalNamesType

// SchemeName ...
type SchemeName *InternationalNamesType

// SchemeInformationURI ...
type SchemeInformationURI *NonEmptyMultiLangURIListType

// SchemeTypeCommunityRules ...
type SchemeTypeCommunityRules *NonEmptyMultiLangURIListType

// SchemeTerritory ...
type SchemeTerritory string

// PolicyOrLegalNotice ...
type PolicyOrLegalNotice *PolicyOrLegalnoticeType

// PolicyOrLegalnoticeType ...
type PolicyOrLegalnoticeType struct {
	LoTEPolicy      []*NonEmptyMultiLangURIType `xml:"LoTEPolicy"`
	LoTELegalNotice []*MultiLangStringType      `xml:"LoTELegalNotice"`
}

// NextUpdate ...
type NextUpdate *NextUpdateType

// NextUpdateType ...
type NextUpdateType struct {
	DateTime *string `xml:"dateTime"`
}

// PointersToOtherLoTE ...
type PointersToOtherLoTE *OtherLoTEPointersType

// OtherLoTEPointersType ...
type OtherLoTEPointersType struct {
	LoteOtherLoTEPointer []*OtherLoTEPointerType `xml:"OtherLoTEPointer"`
}

// OtherLoTEPointer ...
type OtherLoTEPointer *OtherLoTEPointerType

// OtherLoTEPointerType ...
type OtherLoTEPointerType struct {
	LoteServiceDigitalIdentities *ServiceDigitalIdentityListType `xml:"ServiceDigitalIdentities"`
	LoTELocation                 string                          `xml:"LoTELocation"`
	LoteAdditionalInformation    *AdditionalInformationType      `xml:"AdditionalInformation"`
}

// ServiceDigitalIdentities ...
type ServiceDigitalIdentities *ServiceDigitalIdentityListType

// ServiceDigitalIdentityListType ...
type ServiceDigitalIdentityListType struct {
	LoteServiceDigitalIdentity []*DigitalIdentityListType `xml:"ServiceDigitalIdentity"`
}

// AdditionalInformation ...
type AdditionalInformation *AdditionalInformationType

// AdditionalInformationType ...
type AdditionalInformationType struct {
	TextualInformation []*MultiLangStringType `xml:"TextualInformation"`
	OtherInformation   []*AnyType             `xml:"OtherInformation"`
}

// DistributionPoints ...
type DistributionPoints *NonEmptyURIListType

// TrustedEntity ...
type TrustedEntity *TEType

// TEType ...
type TEType struct {
	LoteTrustedEntityInformation *TrustedEntityInformationType  `xml:"TrustedEntityInformation"`
	LoteTrustedEntityServices    *TrustedEntityServicesListType `xml:"TrustedEntityServices"`
}

// TrustedEntityInformation ...
type TrustedEntityInformation *TrustedEntityInformationType

// TrustedEntityInformationType ...
type TrustedEntityInformationType struct {
	TEName                  *InternationalNamesType       `xml:"TEName"`
	TETradeName             *InternationalNamesType       `xml:"TETradeName"`
	TEAddress               *AddressType                  `xml:"TEAddress"`
	TEInformationURI        *NonEmptyMultiLangURIListType `xml:"TEInformationURI"`
	TEInformationExtensions *ExtensionsListType           `xml:"TEInformationExtensions"`
}

// TrustedEntityServices ...
type TrustedEntityServices *TrustedEntityServicesListType

// TrustedEntityServicesListType ...
type TrustedEntityServicesListType struct {
	LoteTrustedEntityService []*TrustedEntityServiceType `xml:"TrustedEntityService"`
}

// TrustedEntityService ...
type TrustedEntityService *TrustedEntityServiceType

// TrustedEntityServiceType ...
type TrustedEntityServiceType struct {
	LoteServiceInformation *TEServiceInformationType `xml:"ServiceInformation"`
	LoteServiceHistory     *ServiceHistoryType       `xml:"ServiceHistory"`
}

// ServiceInformation ...
type ServiceInformation *TEServiceInformationType

// TEServiceInformationType ...
type TEServiceInformationType struct {
	LoteServiceTypeIdentifier    *string                       `xml:"ServiceTypeIdentifier"`
	ServiceName                  *InternationalNamesType       `xml:"ServiceName"`
	LoteServiceDigitalIdentity   *DigitalIdentityListType      `xml:"ServiceDigitalIdentity"`
	LoteServiceStatus            *string                       `xml:"ServiceStatus"`
	StatusStartingTime           *string                       `xml:"StatusStartingTime"`
	SchemeServiceDefinitionURI   *NonEmptyMultiLangURIListType `xml:"SchemeServiceDefinitionURI"`
	LoteServiceSupplyPoints      *ServiceSupplyPointsType      `xml:"ServiceSupplyPoints"`
	TEServiceDefinitionURI       *NonEmptyMultiLangURIListType `xml:"TEServiceDefinitionURI"`
	ServiceInformationExtensions *ExtensionsListType           `xml:"ServiceInformationExtensions"`
}

// ServiceStatus ...
type ServiceStatus string

// ServiceSupplyPoints ...
type ServiceSupplyPoints *ServiceSupplyPointsType

// ServiceSupplyPointsType ...
type ServiceSupplyPointsType struct {
	ServiceSupplyPoint []*AttributedNonEmptyURIType `xml:"ServiceSupplyPoint"`
}

// ServiceTypeIdentifier ...
type ServiceTypeIdentifier string

// ServiceDigitalIdentity ...
type ServiceDigitalIdentity *DigitalIdentityListType

// DigitalIdentityListType ...
type DigitalIdentityListType struct {
	DigitalId []*DigitalIdentityType `xml:"DigitalId"`
}

// DigitalIdentityType ...
type DigitalIdentityType struct {
	X509Certificate *string   `xml:"X509Certificate"`
	X509SubjectName *string   `xml:"X509SubjectName"`
	DsKeyValue      *KeyValue `xml:"ds:KeyValue"`
	X509SKI         *string   `xml:"X509SKI"`
	OtherId         *AnyType  `xml:"OtherId"`
}

// ServiceHistory ...
type ServiceHistory *ServiceHistoryType

// ServiceHistoryType ...
type ServiceHistoryType struct {
	LoteServiceHistoryInstance []*ServiceHistoryInstanceType `xml:"ServiceHistoryInstance"`
}

// ServiceHistoryInstance ...
type ServiceHistoryInstance *ServiceHistoryInstanceType

// ServiceHistoryInstanceType ...
type ServiceHistoryInstanceType struct {
	LoteServiceTypeIdentifier    *string                  `xml:"ServiceTypeIdentifier"`
	ServiceName                  *InternationalNamesType  `xml:"ServiceName"`
	LoteServiceDigitalIdentity   *DigitalIdentityListType `xml:"ServiceDigitalIdentity"`
	LoteServiceStatus            string                   `xml:"ServiceStatus"`
	StatusStartingTime           string                   `xml:"StatusStartingTime"`
	ServiceInformationExtensions *ExtensionsListType      `xml:"ServiceInformationExtensions"`
}
