on: [push, pull_request]
name: Test
permissions: write-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
         go-version-file: go.mod
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y softhsm2 opensc xsltproc
    - name: run tests
      run: make test
    - name: generate test coverage
      run: go test -tags softhsm ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
    - name: check test coverage
      uses: vladopajic/go-test-coverage@v2
      with:
        debug: true
        config: ./.testcoverage.yml
        git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
        git-branch: badges
